"""Domain models and rules independent of UI and infrastructure."""

from dlsite_organizer.domain.bonus import BonusEvidence, BonusEvidenceSnapshot
from dlsite_organizer.domain.candidate import (
    CandidateEvidence,
    CandidateEvidenceKind,
    CandidateEvidencePolarity,
    CandidatePolicyDescriptor,
    CandidatePolicyProvenance,
    CandidateRelation,
    CandidateSearchResult,
    CandidateSearchState,
    CandidateSnapshotSource,
    CandidateType,
    KnownWorkSnapshot,
)
from dlsite_organizer.domain.evaluation import (
    EvaluationExportRecord,
    EvaluationMetricState,
    EvaluationRecord,
    EvaluationRecordState,
    EvaluationSummary,
    EvidenceGroupSummary,
    InvalidSnapshotReview,
    PolicyDistributionSummary,
    RelationTypeCount,
)
from dlsite_organizer.domain.manual_review import (
    MANUAL_RELATION_DIRECTIONALITY,
    CandidateEvidenceSnapshot,
    CandidateReviewOutcome,
    ManualRelationReview,
    ManualRelationType,
    ManualReviewEvent,
    ManualReviewProvenance,
    is_manual_relation_directional,
    parse_candidate_evidence_snapshot,
)
from dlsite_organizer.domain.organizer import (
    RenamePlan,
    RenamePlanStatus,
    ScanCandidate,
    ScanCandidateStatus,
    ScanResult,
    ScanSkipped,
    ScanSkipReason,
)
from dlsite_organizer.domain.relation import TranslationRole, WorkRelation
from dlsite_organizer.domain.rename_execution import (
    ExecutionResult,
    ExecutionStatus,
    RenameExecutionResult,
    RenameOperation,
    RenameTransaction,
    TransactionStatus,
    UndoResult,
    UndoStatus,
)
from dlsite_organizer.domain.work import Work
from dlsite_organizer.domain.work_code import WorkCode, WorkCodeError, extract_work_codes

__all__ = [
    "MANUAL_RELATION_DIRECTIONALITY",
    "BonusEvidence",
    "BonusEvidenceSnapshot",
    "CandidateEvidence",
    "CandidateEvidenceKind",
    "CandidateEvidencePolarity",
    "CandidateEvidenceSnapshot",
    "CandidatePolicyDescriptor",
    "CandidatePolicyProvenance",
    "CandidateRelation",
    "CandidateReviewOutcome",
    "CandidateSearchResult",
    "CandidateSearchState",
    "CandidateSnapshotSource",
    "CandidateType",
    "EvaluationExportRecord",
    "EvaluationMetricState",
    "EvaluationRecord",
    "EvaluationRecordState",
    "EvaluationSummary",
    "EvidenceGroupSummary",
    "ExecutionResult",
    "ExecutionStatus",
    "InvalidSnapshotReview",
    "KnownWorkSnapshot",
    "ManualRelationReview",
    "ManualRelationType",
    "ManualReviewEvent",
    "ManualReviewProvenance",
    "PolicyDistributionSummary",
    "RelationTypeCount",
    "RenameExecutionResult",
    "RenameOperation",
    "RenamePlan",
    "RenamePlanStatus",
    "RenameTransaction",
    "ScanCandidate",
    "ScanCandidateStatus",
    "ScanResult",
    "ScanSkipReason",
    "ScanSkipped",
    "TransactionStatus",
    "TranslationRole",
    "UndoResult",
    "UndoStatus",
    "Work",
    "WorkCode",
    "WorkCodeError",
    "WorkRelation",
    "extract_work_codes",
    "is_manual_relation_directional",
    "parse_candidate_evidence_snapshot",
]
