#pragma once

#include <cstddef>
#include <cstdint>

namespace dlsite::shell {

// Generated once for the v1.2.0 native helper spike.  It is the stable
// project identity and must not be regenerated by a build.
inline constexpr wchar_t kClassIdString[] = L"{031255AF-20D8-4EE9-AC4C-D8CE7D3E154B}";

inline constexpr std::size_t kMaxQuickRenameItems = 32;
inline constexpr std::size_t kMaxQuickRenamePathLength = 32767;
inline constexpr std::size_t kMaxRequestFrameSize = 256 * 1024;
inline constexpr std::size_t kMaxResponseFrameSize = 4 * 1024;
inline constexpr std::size_t kMaxRequestIdLength = 64;
inline constexpr std::size_t kMaxReplyDetailLength = 512;
inline constexpr std::uint32_t kProtocolVersion = 1;
inline constexpr std::uint32_t kFrameHeaderSize = 4;

inline constexpr unsigned long kInitialConnectDeadlineMs = 500;
inline constexpr unsigned long kStartupConnectDeadlineMs = 5000;
inline constexpr unsigned long kAckDeadlineMs = 2000;
inline constexpr unsigned long kConnectRetryIntervalMs = 25;
inline constexpr unsigned long kHelperIdleLifetimeMs = 10'000;

}  // namespace dlsite::shell
